---
- name: Load a variable file based on the OS type.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Set up local user account
  include_tasks:
    file: setup-user.yml
    apply:
      become: true

- name: Install Deno
  include_tasks:
    file: deno.yml
    apply:
      become: true
  when: strfry_policies_enabled
        
- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ strfry_build_dependencies }}"
    state: present
  become: true

- name: Run build tasks as the ansible user (must not be root)
  include_tasks: build.yml

- name: Proceeding with installation
  include_tasks:
    file: install.yml
    apply:
      become: true