---
- name: Load a variable file based on the OS type.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install Deno
  ansible.builtin.include_tasks:
    file: deno.yml
    apply:
      tags: deno
      become: true
        
- name: Install build dependencies
  ansible.builtin.package:
    name: "{{ strfry_build_dependencies }}"
    state: present
  become: true

- name: Set up local user account
  import_tasks: setup-user.yml

- name: Run build tasks
  import_tasks: build.yml
  tags: build

- name: Proceeding with installation
  import_tasks: install.yml